In [15]:
import yaml
with open('../data/data_desription.yaml', 'r') as stream:   # 'document.yaml' contains a single YAML document.
    meta=yaml.load(stream)

In [2]:
len(meta)

78

In [3]:
cat_to_ord={'nan':0,'NA':0,'Po':1,'Fa':2,'TA':3,'Gd':4,'Ex':5, 'No':1,'Mn':2,'Av':3,'Unf':1,'LwQ':2,'Rec':3,'BLQ':4,'ALQ':5,'GLQ':6}

In [4]:
%matplotlib widget
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

In [5]:
data = pd.read_csv("../data/train.csv")#to_numeric 
data.sort_values(by=['YrSold'], inplace=True, ascending=True)

In [6]:
np.array(data['MasVnrArea'])

array([  0., 236.,  68., ..., 226.,   0.,   0.])

In [19]:
new_data={}
for name,m in meta.items():

    if m.get('type') == 'categorical':
        d = methods.get(m.get('method'))(data[name],name)
        if type(d) == dict:
            
            new_data = {**new_data, **d}
        else:
            new_data[name]=d

        
    if m.get('type') == 'numerical':
        new_data[name]=np.array(pd.to_numeric(data[name]))
    if m.get('NaNis') == 'median':
        print(name)
        
        new_data[name][np.isnan(new_data[name])] = np.median(new_data[name][np.isnan(new_data[name])==False])
    if m.get('NaNis') == 'mean':
        new_data[name]=np.array(pd.to_numeric(data[name]))
        new_data[name][np.isnan(new_data[name])] = np.mean(new_data[name][np.isnan(new_data[name])==False]) 
    if m.get('NaNis') == 0:
        new_data[name]=np.array(pd.to_numeric(data[name]))
        new_data[name][np.isnan(new_data[name])] = 0
    

MasVnrArea
GarageYrBlt
GarageCars
GarageQual


In [8]:
def Ordinal(data,name):
    out=np.array([cat_to_ord.get(d,np.NaN) for d in data])
    out[np.isnan(out)]=np.median(out)
    return out

In [9]:
def OneHot(column,name):
    temp = pd.get_dummies(column)

    return {name+'_'+str(col):temp[col].values for col in temp }

In [10]:
def numerical(data,name):
    return np.array(data)

In [11]:
methods={'OneHot':OneHot,'Ordinal':Ordinal,None:numerical}

In [13]:
new_data

{'MSSubClass_20': array([0, 0, 1, ..., 1, 0, 0], dtype=uint8),
 'MSSubClass_30': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_40': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_45': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_50': array([0, 0, 0, ..., 0, 0, 1], dtype=uint8),
 'MSSubClass_60': array([1, 0, 0, ..., 0, 1, 0], dtype=uint8),
 'MSSubClass_70': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_75': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_80': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_85': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_90': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_120': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_160': array([0, 1, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_180': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSSubClass_190': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'MSZoning_C (all)': array([0, 0, 0, ..., 0, 0, 0],

In [22]:
new_data['YrSold']

array([2006, 2006, 2006, ..., 2010, 2010, 2010])

array([1992., 1980., 2006., ..., 2005., 2004., 1969.])